name: Publish Unity Embedded Package

on:
  workflow_call:
    inputs:
      directory:
        description: 'Directory where package is located'
        required: true
        type: string
      registry-set:
        description: 'NPM registry credentials for npm set command. e.g "//npm.pkg.github.com/" - Do not include auth token'
        required: true
        type: string
      registry-url:
        description: 'NPM registry url to publish the package to. e.g "https://npm.pkg.github.com/@your-username"'
        required: true
        type: string
    secrets: 
      AUTH_TOKEN:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Login to npm
        run: npm set ${{ inputs.registry-set }}:_authToken=${{ secrets.AUTH_TOKEN }}

      - name: Publish packages
        run: npm publish ${{ inputs.directory }} --registry ${{ inputs.registry-url }}