# Template/reusable workflow
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Build with Unity Cloud
on:
  workflow_call:
    inputs:
      UnityCloudOrganisation:
        required: true
        type: string
      UnityCloudProject:
        required: true
        type: string
      UnityCloudBuildTarget:
        required: true
        type: string
      UnityCloudTargetPlatform:
        required: false
        type: string
        #deprecationMessage: "UnityCloudTargetPlatform is no longer needed and has no effect." # gr: cannot deprecate workflow inputs, just action inputs
      UnityCloudExistingBuildNumber:
        required: false
        type: string # this should be a number, but to allow the input to be used from a workflow_dispatch input, numbers dont work
      
      DownloadBinaryToArtifact:
        required: false
        type: boolean
        
      ReportShareUrl:
        required: false
        type: boolean
    
    secrets:
      UnityCloudBuildApiKey:
        required: true

jobs:
  Build:
    runs-on: ubuntu-22.04
    outputs:
      share_url: ${{ steps.build.outputs.SHARE_URL }}
      artifact_filepath: ${{ steps.build.outputs.ARTIFACT_FILEPATH }}
      artifact_filename: ${{ steps.build.outputs.ARTIFACT_FILENAME }}
    
    steps:

      - name: Build with Unity Cloud Build
        uses: condensereality/UnityCloudBuildAction@main
        id: build
        with:
          unity_cloud_build_api_key: ${{ secrets.UnityCloudBuildApiKey }}
          unity_cloud_build_org_id: ${{ inputs.UnityCloudOrganisation }}
          unity_cloud_build_project_id: ${{ inputs.UnityCloudProject }}
          unity_cloud_build_polling_interval: 60
          unity_cloud_build_primary_target: ${{ inputs.UnityCloudBuildTarget }}
          unity_cloud_build_download_binary: ${{ inputs.DownloadBinaryToArtifact }}
          unity_cloud_build_create_share: ${{ inputs.ReportShareUrl }}
          # github.ref is the fully formed ref, eg refs/pull/6/merge or refs/tag/v0.1.2
          # github.head_ref is present in pull requests, and is the SOURCE branch (eg. YourFeatureBranch)
          # github.base_ref is present in pull requests, and is the TARGET branch (eg. main)
          unity_cloud_build_github_branch_ref: ${{ github.ref }}
          unity_cloud_build_github_head_ref: ${{ github.head_ref }}
          unity_cloud_build_github_commit_sha: ${{ github.sha }}
          unity_cloud_build_use_existing_build_number: ${{ inputs.UnityCloudExistingBuildNumber }}

      - name: Store binary as artifact
        if: ${{ inputs.DownloadBinaryToArtifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.ARTIFACT_FILENAME }}
          path: ${{ steps.build.outputs.ARTIFACT_FILEPATH }}
          if-no-files-found: error